psd_to_linesape('C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\Teraxion_UnlockedT2.csv',...
    'C:\Users\erod2\projects\Capstone\Team\junk_laser_data\LXM-U_Trial2.csv',...
    'C:\Users\erod2\projects\Capstone\Team\junk_laser_data\LXM-U_Trial3.csv',...
    'C:\Users\erod2\projects\Capstone\Team\junk_laser_data\LXM-U_Trial4_50MHz.csv')

%    'C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\Teraxion_Unlocked.csv'