psd_to_lineshape('C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\DFB_XMHz_Trial7.csv',...
    'C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\DFB_XMHz_Trial6.csv',...
    'C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\DFB_XMHz_Trial5.csv',...
    'C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\DFB_XMHz_Trial4.csv',...
    'C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\DFB_XMHz_Trial3.csv',...
    'C:\Users\erod2\projects\Capstone\Team\Pound-Drever-Hall\DFB_Trial1.csv')