// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ pdh_core__DOT__clk;
        CData/*0:0*/ pdh_core__DOT__rst_i;
        CData/*0:0*/ pdh_core__DOT__u_strobe_edge_detector__DOT__clk;
        CData/*0:0*/ pdh_core__DOT__u_strobe_edge_detector__DOT__rst;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__clk;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__clk;
        CData/*0:0*/ pdh_core__DOT__u_pid__DOT__clk;
        CData/*0:0*/ pdh_core__DOT__u_dma_edge_detector__DOT__clk;
        CData/*0:0*/ pdh_core__DOT__u_dma_edge_detector__DOT__rst;
        CData/*0:0*/ pdh_core__DOT__u_bram_edge_detector__DOT__clk;
        CData/*0:0*/ pdh_core__DOT__u_bram_edge_detector__DOT__rst;
        VL_IN8(clk,0,0);
        VL_OUT8(adc_csn_o,0,0);
        VL_OUT8(dac_wrt_o,0,0);
        VL_OUT8(dac_rst_o,0,0);
        VL_OUT8(dac_sel_o,0,0);
        VL_OUT8(led_o,7,0);
        VL_OUT8(rst_o,0,0);
        VL_OUT8(dma_enable_o,0,0);
        VL_OUT8(bram_enable_o,0,0);
        VL_IN8(dma_ready_i,0,0);
        VL_IN8(bram_ready_i,0,0);
        CData/*0:0*/ pdh_core__DOT__adc_csn_o;
        CData/*0:0*/ pdh_core__DOT__dac_wrt_o;
        CData/*0:0*/ pdh_core__DOT__dac_rst_o;
        CData/*0:0*/ pdh_core__DOT__dac_sel_o;
        CData/*7:0*/ pdh_core__DOT__led_o;
        CData/*0:0*/ pdh_core__DOT__rst_o;
        CData/*0:0*/ pdh_core__DOT__dma_enable_o;
        CData/*0:0*/ pdh_core__DOT__bram_enable_o;
        CData/*0:0*/ pdh_core__DOT__dma_ready_i;
        CData/*0:0*/ pdh_core__DOT__bram_ready_i;
        CData/*3:0*/ pdh_core__DOT__cmd_w;
        CData/*0:0*/ pdh_core__DOT__strobe_bit_w;
        CData/*0:0*/ pdh_core__DOT__strobe_edge_w;
        CData/*7:0*/ pdh_core__DOT__led_r;
        CData/*7:0*/ pdh_core__DOT__next_led_w;
        CData/*3:0*/ pdh_core__DOT__alpha_w;
        CData/*3:0*/ pdh_core__DOT__alpha_r;
        CData/*4:0*/ pdh_core__DOT__satwidth_r;
        CData/*4:0*/ pdh_core__DOT__satwidth_w;
        CData/*0:0*/ pdh_core__DOT__pid_enable_w;
        CData/*0:0*/ pdh_core__DOT__pid_enable_r;
        CData/*3:0*/ pdh_core__DOT__pid_coeff_select_w;
        CData/*0:0*/ pdh_core__DOT__dac_sel_r;
        CData/*0:0*/ pdh_core__DOT__next_dac_sel_w;
        CData/*0:0*/ pdh_core__DOT__nco_en_r;
        CData/*0:0*/ pdh_core__DOT__nco_en_w;
        CData/*0:0*/ pdh_core__DOT__nco_inv_r;
        CData/*0:0*/ pdh_core__DOT__nco_inv_w;
        CData/*0:0*/ pdh_core__DOT__nco_sub_r;
        CData/*0:0*/ pdh_core__DOT__nco_sub_w;
        CData/*2:0*/ pdh_core__DOT__pid_sel_r;
        CData/*2:0*/ pdh_core__DOT__next_pid_sel_w;
        CData/*2:0*/ pdh_core__DOT__dac1_dat_sel_r;
        CData/*2:0*/ pdh_core__DOT__next_dac1_dat_sel_w;
        CData/*2:0*/ pdh_core__DOT__dac2_dat_sel_r;
        CData/*2:0*/ pdh_core__DOT__next_dac2_dat_sel_w;
        CData/*3:0*/ pdh_core__DOT__frame_code_r;
        CData/*3:0*/ pdh_core__DOT__next_frame_code_w;
        CData/*2:0*/ pdh_core__DOT__nco_coeff_select_w;
        CData/*0:0*/ pdh_core__DOT__dma_ready_edge_w;
        CData/*0:0*/ pdh_core__DOT__dma_ready_1ff;
        CData/*0:0*/ pdh_core__DOT__dma_ready_2ff;
    };
    struct {
        CData/*0:0*/ pdh_core__DOT__dma_ready_3ff;
        CData/*0:0*/ pdh_core__DOT__bram_ready_edge_w;
        CData/*0:0*/ pdh_core__DOT__bram_ready_r;
        CData/*0:0*/ pdh_core__DOT__bram_edge_acquired_r;
        CData/*0:0*/ pdh_core__DOT__next_bram_edge_acquired_w;
        CData/*0:0*/ pdh_core__DOT__dma_enable_r;
        CData/*0:0*/ pdh_core__DOT__next_dma_enable_w;
        CData/*0:0*/ pdh_core__DOT__bram_enable_r;
        CData/*0:0*/ pdh_core__DOT__next_bram_enable_w;
        CData/*1:0*/ pdh_core__DOT__dma_state_r;
        CData/*1:0*/ pdh_core__DOT__next_dma_state_w;
        CData/*0:0*/ pdh_core__DOT__rst_sync_r;
        CData/*0:0*/ pdh_core__DOT__rst_pipe1_r;
        CData/*0:0*/ pdh_core__DOT__rst_sync_ne_r;
        CData/*0:0*/ pdh_core__DOT__rst_pipe1_ne_r;
        CData/*0:0*/ pdh_core__DOT__u_strobe_edge_detector__DOT__D;
        CData/*0:0*/ pdh_core__DOT__u_strobe_edge_detector__DOT__Q;
        CData/*0:0*/ pdh_core__DOT__u_strobe_edge_detector__DOT__prev_D;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__enable_i;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__rst_i;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__invert_i;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__sub_i;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__invert_r;
        CData/*0:0*/ pdh_core__DOT__u_nco__DOT__sub_r;
        CData/*1:0*/ pdh_core__DOT__u_nco__DOT__state1_w;
        CData/*1:0*/ pdh_core__DOT__u_nco__DOT__state2_w;
        CData/*0:0*/ pdh_core__DOT__u_pid__DOT__rst;
        CData/*3:0*/ pdh_core__DOT__u_pid__DOT__alpha_i;
        CData/*4:0*/ pdh_core__DOT__u_pid__DOT__satwidth_i;
        CData/*0:0*/ pdh_core__DOT__u_pid__DOT__enable_i;
        CData/*3:0*/ pdh_core__DOT__u_pid__DOT__alpha_r;
        CData/*4:0*/ pdh_core__DOT__u_pid__DOT__satwidth_r;
        CData/*0:0*/ pdh_core__DOT__u_pid__DOT__tick1_w;
        CData/*0:0*/ pdh_core__DOT__u_pid__DOT__tick1_r;
        CData/*0:0*/ pdh_core__DOT__u_pid__DOT__tick2_r;
        CData/*4:0*/ pdh_core__DOT__u_pid__DOT__next_satwidth_w;
        CData/*0:0*/ pdh_core__DOT__u_dma_edge_detector__DOT__D;
        CData/*0:0*/ pdh_core__DOT__u_dma_edge_detector__DOT__Q;
        CData/*0:0*/ pdh_core__DOT__u_dma_edge_detector__DOT__prev_D;
        CData/*0:0*/ pdh_core__DOT__u_bram_edge_detector__DOT__D;
        CData/*0:0*/ pdh_core__DOT__u_bram_edge_detector__DOT__Q;
        CData/*0:0*/ pdh_core__DOT__u_bram_edge_detector__DOT__prev_D;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__rst_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_strobe_edge_detector__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_strobe_edge_detector__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_nco__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_pid__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_dma_edge_detector__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_dma_edge_detector__DOT__rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_bram_edge_detector__DOT__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pdh_core__DOT__u_bram_edge_detector__DOT__rst__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(adc_dat_a_i,13,0);
        VL_IN16(adc_dat_b_i,13,0);
        VL_OUT16(dac_dat_o,13,0);
        SData/*13:0*/ pdh_core__DOT__adc_dat_a_i;
        SData/*13:0*/ pdh_core__DOT__adc_dat_b_i;
        SData/*13:0*/ pdh_core__DOT__dac_dat_o;
        SData/*15:0*/ pdh_core__DOT__i_feed_w;
        SData/*15:0*/ pdh_core__DOT__q_feed_w;
    };
    struct {
        SData/*15:0*/ pdh_core__DOT__i_feed_r;
        SData/*15:0*/ pdh_core__DOT__q_feed_r;
        SData/*15:0*/ pdh_core__DOT__cos_theta_r;
        SData/*15:0*/ pdh_core__DOT__next_cos_theta_w;
        SData/*15:0*/ pdh_core__DOT__rot_cos_theta_r;
        SData/*15:0*/ pdh_core__DOT__next_rot_cos_theta_w;
        SData/*15:0*/ pdh_core__DOT__sin_theta_r;
        SData/*15:0*/ pdh_core__DOT__next_sin_theta_w;
        SData/*15:0*/ pdh_core__DOT__rot_sin_theta_r;
        SData/*15:0*/ pdh_core__DOT__next_rot_sin_theta_w;
        SData/*15:0*/ pdh_core__DOT__kp_r;
        SData/*15:0*/ pdh_core__DOT__kd_r;
        SData/*15:0*/ pdh_core__DOT__ki_r;
        SData/*15:0*/ pdh_core__DOT__kp_w;
        SData/*15:0*/ pdh_core__DOT__kd_w;
        SData/*15:0*/ pdh_core__DOT__ki_w;
        SData/*13:0*/ pdh_core__DOT__sp_w;
        SData/*13:0*/ pdh_core__DOT__sp_r;
        SData/*13:0*/ pdh_core__DOT__dec_w;
        SData/*13:0*/ pdh_core__DOT__dec_r;
        SData/*13:0*/ pdh_core__DOT__pid_out_w;
        SData/*15:0*/ pdh_core__DOT__base_bus;
        SData/*15:0*/ pdh_core__DOT__pid_payload_w;
        SData/*13:0*/ pdh_core__DOT__dac1_dat_r;
        SData/*13:0*/ pdh_core__DOT__next_dac1_dat_w;
        SData/*13:0*/ pdh_core__DOT__dac2_dat_r;
        SData/*13:0*/ pdh_core__DOT__next_dac2_dat_w;
        SData/*11:0*/ pdh_core__DOT__nco_stride_r;
        SData/*11:0*/ pdh_core__DOT__nco_stride_w;
        SData/*11:0*/ pdh_core__DOT__nco_shift_r;
        SData/*11:0*/ pdh_core__DOT__nco_shift_w;
        SData/*15:0*/ pdh_core__DOT__nco_out1_w;
        SData/*15:0*/ pdh_core__DOT__nco_out2_w;
        SData/*15:0*/ pdh_core__DOT__nco_out1_r;
        SData/*15:0*/ pdh_core__DOT__nco_out2_r;
        SData/*13:0*/ pdh_core__DOT__nco_feed1_r;
        SData/*13:0*/ pdh_core__DOT__nco_feed2_r;
        SData/*13:0*/ pdh_core__DOT__nco_feed1_w;
        SData/*13:0*/ pdh_core__DOT__nco_feed2_w;
        SData/*11:0*/ pdh_core__DOT__addr1_w;
        SData/*11:0*/ pdh_core__DOT__addr2_w;
        SData/*13:0*/ pdh_core__DOT__phi1_w;
        SData/*13:0*/ pdh_core__DOT__phi2_w;
        SData/*13:0*/ pdh_core__DOT__dac1_feed_w;
        SData/*13:0*/ pdh_core__DOT__dac2_feed_w;
        SData/*15:0*/ pdh_core__DOT__pid_in_w;
        SData/*15:0*/ pdh_core__DOT__err_tap_w;
        SData/*15:0*/ pdh_core__DOT__perr_tap_w;
        SData/*15:0*/ pdh_core__DOT__derr_tap_w;
        SData/*15:0*/ pdh_core__DOT__ierr_tap_w;
        SData/*15:0*/ pdh_core__DOT__adc_dat_a_16s_w;
        SData/*15:0*/ pdh_core__DOT__adc_dat_b_16s_w;
        SData/*15:0*/ pdh_core__DOT__adc_dat_a_16s_r;
        SData/*15:0*/ pdh_core__DOT__adc_dat_b_16s_r;
        SData/*14:0*/ pdh_core__DOT__tmp_s_a;
        SData/*14:0*/ pdh_core__DOT__tmp_s_b;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__stride_i;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__shift_i;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__out1_o;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__out2_o;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__addr1_o;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__addr2_o;
        SData/*13:0*/ pdh_core__DOT__u_nco__DOT__phi1_o;
        SData/*13:0*/ pdh_core__DOT__u_nco__DOT__phi2_o;
    };
    struct {
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__stride_r;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__shift_r;
        SData/*13:0*/ pdh_core__DOT__u_nco__DOT__phi1_r;
        SData/*13:0*/ pdh_core__DOT__u_nco__DOT__next_phi1_w;
        SData/*13:0*/ pdh_core__DOT__u_nco__DOT__phi2_w;
        SData/*13:0*/ pdh_core__DOT__u_nco__DOT__phi1_pipe1_r;
        SData/*13:0*/ pdh_core__DOT__u_nco__DOT__phi2_pipe1_r;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__addr1_w;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__addr2_w;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__addr1_r;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__addr2_r;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__rom1_lookup_w;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__rom2_lookup_w;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__rom1_signed_w;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__rom1_signed_r;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__rom2_intermediate_w;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__rom2_signed_w;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__rom2_signed_r;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__addr1;
        SData/*11:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__addr2;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__dout1;
        SData/*15:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__dout2;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__kp_i;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__kd_i;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__ki_i;
        SData/*13:0*/ pdh_core__DOT__u_pid__DOT__decimate_i;
        SData/*13:0*/ pdh_core__DOT__u_pid__DOT__sp_i;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__dat_i;
        SData/*13:0*/ pdh_core__DOT__u_pid__DOT__pid_out;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__err_tap;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__perr_tap;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__derr_tap;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__ierr_tap;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__kp_r;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__kd_r;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__ki_r;
        SData/*13:0*/ pdh_core__DOT__u_pid__DOT__sp_r;
        SData/*13:0*/ pdh_core__DOT__u_pid__DOT__decimate_r;
        SData/*13:0*/ pdh_core__DOT__u_pid__DOT__cnt_r;
        SData/*13:0*/ pdh_core__DOT__u_pid__DOT__next_cnt_w;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__error_w;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__error_pipe1_r;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__yk_w;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__yk_r;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__p_error_shifted_w;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__d_error_shifted_w;
        SData/*15:0*/ pdh_core__DOT__u_pid__DOT__i_error_shifted_w;
        VL_IN(axi_from_ps_i,31,0);
        VL_OUT(axi_to_ps_o,31,0);
        VL_OUT(dma_decimation_code_o,21,0);
        IData/*31:0*/ pdh_core__DOT__axi_from_ps_i;
        IData/*31:0*/ pdh_core__DOT__axi_to_ps_o;
        IData/*21:0*/ pdh_core__DOT__dma_decimation_code_o;
        IData/*31:0*/ pdh_core__DOT__axi_from_ps_r;
        IData/*31:0*/ pdh_core__DOT__next_axi_from_ps_w;
        IData/*31:0*/ pdh_core__DOT__axi_1ff_r;
        IData/*31:0*/ pdh_core__DOT__axi_2ff_r;
        IData/*31:0*/ pdh_core__DOT__axi_3ff_r;
        IData/*25:0*/ pdh_core__DOT__data_w;
        IData/*31:0*/ pdh_core__DOT__idle_cb_w;
        IData/*31:0*/ pdh_core__DOT__led_cb_w;
        IData/*31:0*/ pdh_core__DOT__dac_cb_w;
        IData/*31:0*/ pdh_core__DOT__adc_cb_w;
        IData/*31:0*/ pdh_core__DOT__cs_cb_w;
    };
    struct {
        IData/*31:0*/ pdh_core__DOT__set_rot_cb_w;
        IData/*31:0*/ pdh_core__DOT__commit_rot_cb_w;
        IData/*31:0*/ pdh_core__DOT__get_frame_cb_w;
        IData/*31:0*/ pdh_core__DOT__set_pid_cb_w;
        IData/*31:0*/ pdh_core__DOT__set_nco_cb_w;
        IData/*31:0*/ pdh_core__DOT__config_io_cb_w;
        IData/*21:0*/ pdh_core__DOT__dma_decimation_code_r;
        IData/*21:0*/ pdh_core__DOT__next_dma_decimation_code_w;
        IData/*31:0*/ pdh_core__DOT__callback_r;
        IData/*31:0*/ pdh_core__DOT__next_callback_w;
        IData/*31:0*/ pdh_core__DOT__sum_err_tap_w;
        IData/*31:0*/ pdh_core__DOT__i_rot_sat_w;
        IData/*31:0*/ pdh_core__DOT__q_rot_sat_w;
        IData/*31:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__i;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__sum_err_tap;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__sum_error1_w;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__sum_error2_w;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__sum_error_r;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__sat_threshold_w;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__p_error_r;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__p_error_w;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__d_error_r;
        IData/*31:0*/ pdh_core__DOT__u_pid__DOT__d_error_w;
        IData/*19:0*/ pdh_core__DOT__u_pid__DOT__total_error_wide_w;
        IData/*31:0*/ __VactIterCount;
        VL_OUT64(dma_data_o,63,0);
        QData/*63:0*/ pdh_core__DOT__dma_data_o;
        QData/*63:0*/ pdh_core__DOT__dma_data_r;
        QData/*63:0*/ pdh_core__DOT__dma_data_w;
        QData/*32:0*/ pdh_core__DOT__i_rot_w;
        QData/*32:0*/ pdh_core__DOT__q_rot_w;
        QData/*32:0*/ pdh_core__DOT__u_pid__DOT__sum_error_wide_w;
        QData/*47:0*/ pdh_core__DOT__u_pid__DOT__i_error_r;
        QData/*47:0*/ pdh_core__DOT__u_pid__DOT__i_error_w;
        VlUnpacked<SData/*15:0*/, 4096> pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__rom;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<12> __VactTriggered;
    VlTriggerVec<12> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr SData/*14:0*/ pdh_core__DOT__ADC_OFFSET = 0x2000U;
    static constexpr IData/*31:0*/ pdh_core__DOT__ADC_DATA_WIDTH = 0x0000000eU;
    static constexpr IData/*31:0*/ pdh_core__DOT__DAC_DATA_WIDTH = 0x0000000eU;
    static constexpr IData/*31:0*/ pdh_core__DOT__AXI_GPIO_IN_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ pdh_core__DOT__AXI_GPIO_OUT_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ pdh_core__DOT__NUM_MODULES = 2U;
    static constexpr IData/*31:0*/ pdh_core__DOT__CMD_BITS = 4U;
    static constexpr IData/*31:0*/ pdh_core__DOT__CMD_END = 0x0000001dU;
    static constexpr IData/*31:0*/ pdh_core__DOT__CMD_START = 0x0000001aU;
    static constexpr IData/*31:0*/ pdh_core__DOT__DATA_END = 0x00000019U;
    static constexpr IData/*31:0*/ pdh_core__DOT__DATA_START = 0U;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__AW = 0x0000000cU;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__DW = 0x00000010U;
    static constexpr VlWide<6>/*167:0*/ pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__INIT_FILE = {{
        0x2e6d656d, 0x5f313662, 0x34303936, 0x7174725f,
        0x696e655f, 0x00000073
    }};
    static constexpr IData/*31:0*/ pdh_core__DOT__u_pid__DOT__S32_W = 0x00000020U;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_pid__DOT__S16_W = 0x00000010U;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_pid__DOT__DEC_W = 0x0000000eU;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_pid__DOT__W1S = 0x00000020U;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_pid__DOT__W2S = 0x00000021U;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_pid__DOT__W1U = 0x0000000eU;
    static constexpr IData/*31:0*/ pdh_core__DOT__u_pid__DOT__W2U = 0x00000014U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
