// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "Vtop__pch.h"
#include "Vtop.h"
#include "Vtop___024root.h"

// FUNCTIONS
Vtop__Syms::~Vtop__Syms()
{

    // Tear down scope hierarchy
    __Vhier.remove(0, &__Vscope_pdh_core);
    __Vhier.remove(&__Vscope_pdh_core, &__Vscope_pdh_core__u_bram_edge_detector);
    __Vhier.remove(&__Vscope_pdh_core, &__Vscope_pdh_core__u_dma_edge_detector);
    __Vhier.remove(&__Vscope_pdh_core, &__Vscope_pdh_core__u_nco);
    __Vhier.remove(&__Vscope_pdh_core, &__Vscope_pdh_core__u_pid);
    __Vhier.remove(&__Vscope_pdh_core, &__Vscope_pdh_core__u_strobe_edge_detector);
    __Vhier.remove(&__Vscope_pdh_core__u_nco, &__Vscope_pdh_core__u_nco__u_qtr_rom);

}

Vtop__Syms::Vtop__Syms(VerilatedContext* contextp, const char* namep, Vtop* modelp)
    : VerilatedSyms{contextp}
    // Setup internal state of the Syms class
    , __Vm_modelp{modelp}
    // Setup module instances
    , TOP{this, namep}
{
        // Check resources
        Verilated::stackCheck(255);
    // Configure time unit / time precision
    _vm_contextp__->timeunit(-9);
    _vm_contextp__->timeprecision(-12);
    // Setup each module's pointers to their submodules
    // Setup each module's pointer back to symbol table (for public functions)
    TOP.__Vconfigure(true);
    // Setup scopes
    __Vscope_TOP.configure(this, name(), "TOP", "TOP", "<null>", 0, VerilatedScope::SCOPE_OTHER);
    __Vscope_pdh_core.configure(this, name(), "pdh_core", "pdh_core", "pdh_core", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_pdh_core__u_bram_edge_detector.configure(this, name(), "pdh_core.u_bram_edge_detector", "u_bram_edge_detector", "posedge_detector", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_pdh_core__u_dma_edge_detector.configure(this, name(), "pdh_core.u_dma_edge_detector", "u_dma_edge_detector", "posedge_detector", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_pdh_core__u_nco.configure(this, name(), "pdh_core.u_nco", "u_nco", "nco", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_pdh_core__u_nco__u_qtr_rom.configure(this, name(), "pdh_core.u_nco.u_qtr_rom", "u_qtr_rom", "sine_qtr_rom", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_pdh_core__u_pid.configure(this, name(), "pdh_core.u_pid", "u_pid", "pid_core", -9, VerilatedScope::SCOPE_MODULE);
    __Vscope_pdh_core__u_strobe_edge_detector.configure(this, name(), "pdh_core.u_strobe_edge_detector", "u_strobe_edge_detector", "posedge_detector", -9, VerilatedScope::SCOPE_MODULE);

    // Set up scope hierarchy
    __Vhier.add(0, &__Vscope_pdh_core);
    __Vhier.add(&__Vscope_pdh_core, &__Vscope_pdh_core__u_bram_edge_detector);
    __Vhier.add(&__Vscope_pdh_core, &__Vscope_pdh_core__u_dma_edge_detector);
    __Vhier.add(&__Vscope_pdh_core, &__Vscope_pdh_core__u_nco);
    __Vhier.add(&__Vscope_pdh_core, &__Vscope_pdh_core__u_pid);
    __Vhier.add(&__Vscope_pdh_core, &__Vscope_pdh_core__u_strobe_edge_detector);
    __Vhier.add(&__Vscope_pdh_core__u_nco, &__Vscope_pdh_core__u_nco__u_qtr_rom);

    // Setup export functions
    for (int __Vfinal = 0; __Vfinal < 2; ++__Vfinal) {
        __Vscope_TOP.varInsert(__Vfinal,"adc_csn_o", &(TOP.adc_csn_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"adc_dat_a_i", &(TOP.adc_dat_a_i), false, VLVT_UINT16,VLVD_IN|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"adc_dat_b_i", &(TOP.adc_dat_b_i), false, VLVT_UINT16,VLVD_IN|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"axi_from_ps_i", &(TOP.axi_from_ps_i), false, VLVT_UINT32,VLVD_IN|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"axi_to_ps_o", &(TOP.axi_to_ps_o), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_TOP.varInsert(__Vfinal,"bram_enable_o", &(TOP.bram_enable_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"bram_ready_i", &(TOP.bram_ready_i), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"clk", &(TOP.clk), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dac_dat_o", &(TOP.dac_dat_o), false, VLVT_UINT16,VLVD_OUT|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_TOP.varInsert(__Vfinal,"dac_rst_o", &(TOP.dac_rst_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dac_sel_o", &(TOP.dac_sel_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dac_wrt_o", &(TOP.dac_wrt_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dma_data_o", &(TOP.dma_data_o), false, VLVT_UINT64,VLVD_OUT|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_TOP.varInsert(__Vfinal,"dma_decimation_code_o", &(TOP.dma_decimation_code_o), false, VLVT_UINT32,VLVD_OUT|VLVF_PUB_RW,0,1 ,21,0);
        __Vscope_TOP.varInsert(__Vfinal,"dma_enable_o", &(TOP.dma_enable_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"dma_ready_i", &(TOP.dma_ready_i), false, VLVT_UINT8,VLVD_IN|VLVF_PUB_RW,0,0);
        __Vscope_TOP.varInsert(__Vfinal,"led_o", &(TOP.led_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_TOP.varInsert(__Vfinal,"rst_o", &(TOP.rst_o), false, VLVT_UINT8,VLVD_OUT|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"ADC_DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__ADC_DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"ADC_OFFSET", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__ADC_OFFSET))), true, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,14,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"AXI_GPIO_IN_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__AXI_GPIO_IN_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"AXI_GPIO_OUT_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__AXI_GPIO_OUT_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"CMD_BITS", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__CMD_BITS))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"CMD_END", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__CMD_END))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"CMD_START", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__CMD_START))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"DAC_DATA_WIDTH", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__DAC_DATA_WIDTH))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"DATA_END", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__DATA_END))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"DATA_START", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__DATA_START))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"NUM_MODULES", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__NUM_MODULES))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_cb_w", &(TOP.pdh_core__DOT__adc_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_csn_o", &(TOP.pdh_core__DOT__adc_csn_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_dat_a_16s_r", &(TOP.pdh_core__DOT__adc_dat_a_16s_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_dat_a_16s_w", &(TOP.pdh_core__DOT__adc_dat_a_16s_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_dat_a_i", &(TOP.pdh_core__DOT__adc_dat_a_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_dat_b_16s_r", &(TOP.pdh_core__DOT__adc_dat_b_16s_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_dat_b_16s_w", &(TOP.pdh_core__DOT__adc_dat_b_16s_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"adc_dat_b_i", &(TOP.pdh_core__DOT__adc_dat_b_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"addr1_w", &(TOP.pdh_core__DOT__addr1_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"addr2_w", &(TOP.pdh_core__DOT__addr2_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"alpha_r", &(TOP.pdh_core__DOT__alpha_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"alpha_w", &(TOP.pdh_core__DOT__alpha_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"axi_1ff_r", &(TOP.pdh_core__DOT__axi_1ff_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"axi_2ff_r", &(TOP.pdh_core__DOT__axi_2ff_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"axi_3ff_r", &(TOP.pdh_core__DOT__axi_3ff_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"axi_from_ps_i", &(TOP.pdh_core__DOT__axi_from_ps_i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"axi_from_ps_r", &(TOP.pdh_core__DOT__axi_from_ps_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"axi_to_ps_o", &(TOP.pdh_core__DOT__axi_to_ps_o), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"base_bus", &(TOP.pdh_core__DOT__base_bus), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"bram_edge_acquired_r", &(TOP.pdh_core__DOT__bram_edge_acquired_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"bram_enable_o", &(TOP.pdh_core__DOT__bram_enable_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"bram_enable_r", &(TOP.pdh_core__DOT__bram_enable_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"bram_ready_edge_w", &(TOP.pdh_core__DOT__bram_ready_edge_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"bram_ready_i", &(TOP.pdh_core__DOT__bram_ready_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"bram_ready_r", &(TOP.pdh_core__DOT__bram_ready_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"callback_r", &(TOP.pdh_core__DOT__callback_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"clk", &(TOP.pdh_core__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"cmd_w", &(TOP.pdh_core__DOT__cmd_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"commit_rot_cb_w", &(TOP.pdh_core__DOT__commit_rot_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"config_io_cb_w", &(TOP.pdh_core__DOT__config_io_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"cos_theta_r", &(TOP.pdh_core__DOT__cos_theta_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"cs_cb_w", &(TOP.pdh_core__DOT__cs_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac1_dat_r", &(TOP.pdh_core__DOT__dac1_dat_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac1_dat_sel_r", &(TOP.pdh_core__DOT__dac1_dat_sel_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac1_feed_w", &(TOP.pdh_core__DOT__dac1_feed_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac2_dat_r", &(TOP.pdh_core__DOT__dac2_dat_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac2_dat_sel_r", &(TOP.pdh_core__DOT__dac2_dat_sel_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac2_feed_w", &(TOP.pdh_core__DOT__dac2_feed_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac_cb_w", &(TOP.pdh_core__DOT__dac_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac_dat_o", &(TOP.pdh_core__DOT__dac_dat_o), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac_rst_o", &(TOP.pdh_core__DOT__dac_rst_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac_sel_o", &(TOP.pdh_core__DOT__dac_sel_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac_sel_r", &(TOP.pdh_core__DOT__dac_sel_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dac_wrt_o", &(TOP.pdh_core__DOT__dac_wrt_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"data_w", &(TOP.pdh_core__DOT__data_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,25,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dec_r", &(TOP.pdh_core__DOT__dec_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dec_w", &(TOP.pdh_core__DOT__dec_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"derr_tap_w", &(TOP.pdh_core__DOT__derr_tap_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_data_o", &(TOP.pdh_core__DOT__dma_data_o), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_data_r", &(TOP.pdh_core__DOT__dma_data_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_data_w", &(TOP.pdh_core__DOT__dma_data_w), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,63,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_decimation_code_o", &(TOP.pdh_core__DOT__dma_decimation_code_o), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,21,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_decimation_code_r", &(TOP.pdh_core__DOT__dma_decimation_code_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,21,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_enable_o", &(TOP.pdh_core__DOT__dma_enable_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_enable_r", &(TOP.pdh_core__DOT__dma_enable_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_ready_1ff", &(TOP.pdh_core__DOT__dma_ready_1ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_ready_2ff", &(TOP.pdh_core__DOT__dma_ready_2ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_ready_3ff", &(TOP.pdh_core__DOT__dma_ready_3ff), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_ready_edge_w", &(TOP.pdh_core__DOT__dma_ready_edge_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_ready_i", &(TOP.pdh_core__DOT__dma_ready_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"dma_state_r", &(TOP.pdh_core__DOT__dma_state_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"err_tap_w", &(TOP.pdh_core__DOT__err_tap_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"frame_code_r", &(TOP.pdh_core__DOT__frame_code_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"get_frame_cb_w", &(TOP.pdh_core__DOT__get_frame_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"i_feed_r", &(TOP.pdh_core__DOT__i_feed_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"i_feed_w", &(TOP.pdh_core__DOT__i_feed_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"i_rot_sat_w", &(TOP.pdh_core__DOT__i_rot_sat_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"i_rot_w", &(TOP.pdh_core__DOT__i_rot_w), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,32,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"idle_cb_w", &(TOP.pdh_core__DOT__idle_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"ierr_tap_w", &(TOP.pdh_core__DOT__ierr_tap_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"kd_r", &(TOP.pdh_core__DOT__kd_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"kd_w", &(TOP.pdh_core__DOT__kd_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"ki_r", &(TOP.pdh_core__DOT__ki_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"ki_w", &(TOP.pdh_core__DOT__ki_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"kp_r", &(TOP.pdh_core__DOT__kp_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"kp_w", &(TOP.pdh_core__DOT__kp_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"led_cb_w", &(TOP.pdh_core__DOT__led_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"led_o", &(TOP.pdh_core__DOT__led_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"led_r", &(TOP.pdh_core__DOT__led_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_coeff_select_w", &(TOP.pdh_core__DOT__nco_coeff_select_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_en_r", &(TOP.pdh_core__DOT__nco_en_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_en_w", &(TOP.pdh_core__DOT__nco_en_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_feed1_r", &(TOP.pdh_core__DOT__nco_feed1_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_feed1_w", &(TOP.pdh_core__DOT__nco_feed1_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_feed2_r", &(TOP.pdh_core__DOT__nco_feed2_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_feed2_w", &(TOP.pdh_core__DOT__nco_feed2_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_inv_r", &(TOP.pdh_core__DOT__nco_inv_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_inv_w", &(TOP.pdh_core__DOT__nco_inv_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_out1_r", &(TOP.pdh_core__DOT__nco_out1_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_out1_w", &(TOP.pdh_core__DOT__nco_out1_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_out2_r", &(TOP.pdh_core__DOT__nco_out2_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_out2_w", &(TOP.pdh_core__DOT__nco_out2_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_shift_r", &(TOP.pdh_core__DOT__nco_shift_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_shift_w", &(TOP.pdh_core__DOT__nco_shift_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_stride_r", &(TOP.pdh_core__DOT__nco_stride_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_stride_w", &(TOP.pdh_core__DOT__nco_stride_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_sub_r", &(TOP.pdh_core__DOT__nco_sub_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"nco_sub_w", &(TOP.pdh_core__DOT__nco_sub_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_axi_from_ps_w", &(TOP.pdh_core__DOT__next_axi_from_ps_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_bram_edge_acquired_w", &(TOP.pdh_core__DOT__next_bram_edge_acquired_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_bram_enable_w", &(TOP.pdh_core__DOT__next_bram_enable_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_callback_w", &(TOP.pdh_core__DOT__next_callback_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_cos_theta_w", &(TOP.pdh_core__DOT__next_cos_theta_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dac1_dat_sel_w", &(TOP.pdh_core__DOT__next_dac1_dat_sel_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dac1_dat_w", &(TOP.pdh_core__DOT__next_dac1_dat_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dac2_dat_sel_w", &(TOP.pdh_core__DOT__next_dac2_dat_sel_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dac2_dat_w", &(TOP.pdh_core__DOT__next_dac2_dat_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dac_sel_w", &(TOP.pdh_core__DOT__next_dac_sel_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dma_decimation_code_w", &(TOP.pdh_core__DOT__next_dma_decimation_code_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,21,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dma_enable_w", &(TOP.pdh_core__DOT__next_dma_enable_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_dma_state_w", &(TOP.pdh_core__DOT__next_dma_state_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_frame_code_w", &(TOP.pdh_core__DOT__next_frame_code_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_led_w", &(TOP.pdh_core__DOT__next_led_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,7,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_pid_sel_w", &(TOP.pdh_core__DOT__next_pid_sel_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_rot_cos_theta_w", &(TOP.pdh_core__DOT__next_rot_cos_theta_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_rot_sin_theta_w", &(TOP.pdh_core__DOT__next_rot_sin_theta_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"next_sin_theta_w", &(TOP.pdh_core__DOT__next_sin_theta_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"perr_tap_w", &(TOP.pdh_core__DOT__perr_tap_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"phi1_w", &(TOP.pdh_core__DOT__phi1_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"phi2_w", &(TOP.pdh_core__DOT__phi2_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"pid_coeff_select_w", &(TOP.pdh_core__DOT__pid_coeff_select_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"pid_enable_r", &(TOP.pdh_core__DOT__pid_enable_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"pid_enable_w", &(TOP.pdh_core__DOT__pid_enable_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"pid_in_w", &(TOP.pdh_core__DOT__pid_in_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"pid_out_w", &(TOP.pdh_core__DOT__pid_out_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"pid_payload_w", &(TOP.pdh_core__DOT__pid_payload_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"pid_sel_r", &(TOP.pdh_core__DOT__pid_sel_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,2,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"q_feed_r", &(TOP.pdh_core__DOT__q_feed_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"q_feed_w", &(TOP.pdh_core__DOT__q_feed_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"q_rot_sat_w", &(TOP.pdh_core__DOT__q_rot_sat_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"q_rot_w", &(TOP.pdh_core__DOT__q_rot_w), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,32,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rot_cos_theta_r", &(TOP.pdh_core__DOT__rot_cos_theta_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rot_sin_theta_r", &(TOP.pdh_core__DOT__rot_sin_theta_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rst_i", &(TOP.pdh_core__DOT__rst_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rst_o", &(TOP.pdh_core__DOT__rst_o), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rst_pipe1_ne_r", &(TOP.pdh_core__DOT__rst_pipe1_ne_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rst_pipe1_r", &(TOP.pdh_core__DOT__rst_pipe1_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rst_sync_ne_r", &(TOP.pdh_core__DOT__rst_sync_ne_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"rst_sync_r", &(TOP.pdh_core__DOT__rst_sync_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"satwidth_r", &(TOP.pdh_core__DOT__satwidth_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"satwidth_w", &(TOP.pdh_core__DOT__satwidth_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"set_nco_cb_w", &(TOP.pdh_core__DOT__set_nco_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"set_pid_cb_w", &(TOP.pdh_core__DOT__set_pid_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"set_rot_cb_w", &(TOP.pdh_core__DOT__set_rot_cb_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"sin_theta_r", &(TOP.pdh_core__DOT__sin_theta_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"sp_r", &(TOP.pdh_core__DOT__sp_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"sp_w", &(TOP.pdh_core__DOT__sp_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"strobe_bit_w", &(TOP.pdh_core__DOT__strobe_bit_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"strobe_edge_w", &(TOP.pdh_core__DOT__strobe_edge_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"sum_err_tap_w", &(TOP.pdh_core__DOT__sum_err_tap_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"tmp_s_a", &(TOP.pdh_core__DOT__tmp_s_a), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,14,0);
        __Vscope_pdh_core.varInsert(__Vfinal,"tmp_s_b", &(TOP.pdh_core__DOT__tmp_s_b), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,14,0);
        __Vscope_pdh_core__u_bram_edge_detector.varInsert(__Vfinal,"D", &(TOP.pdh_core__DOT__u_bram_edge_detector__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_bram_edge_detector.varInsert(__Vfinal,"Q", &(TOP.pdh_core__DOT__u_bram_edge_detector__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_bram_edge_detector.varInsert(__Vfinal,"clk", &(TOP.pdh_core__DOT__u_bram_edge_detector__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_bram_edge_detector.varInsert(__Vfinal,"prev_D", &(TOP.pdh_core__DOT__u_bram_edge_detector__DOT__prev_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_bram_edge_detector.varInsert(__Vfinal,"rst", &(TOP.pdh_core__DOT__u_bram_edge_detector__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_dma_edge_detector.varInsert(__Vfinal,"D", &(TOP.pdh_core__DOT__u_dma_edge_detector__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_dma_edge_detector.varInsert(__Vfinal,"Q", &(TOP.pdh_core__DOT__u_dma_edge_detector__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_dma_edge_detector.varInsert(__Vfinal,"clk", &(TOP.pdh_core__DOT__u_dma_edge_detector__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_dma_edge_detector.varInsert(__Vfinal,"prev_D", &(TOP.pdh_core__DOT__u_dma_edge_detector__DOT__prev_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_dma_edge_detector.varInsert(__Vfinal,"rst", &(TOP.pdh_core__DOT__u_dma_edge_detector__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"addr1_o", &(TOP.pdh_core__DOT__u_nco__DOT__addr1_o), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"addr1_r", &(TOP.pdh_core__DOT__u_nco__DOT__addr1_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"addr1_w", &(TOP.pdh_core__DOT__u_nco__DOT__addr1_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"addr2_o", &(TOP.pdh_core__DOT__u_nco__DOT__addr2_o), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"addr2_r", &(TOP.pdh_core__DOT__u_nco__DOT__addr2_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"addr2_w", &(TOP.pdh_core__DOT__u_nco__DOT__addr2_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"clk", &(TOP.pdh_core__DOT__u_nco__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"enable_i", &(TOP.pdh_core__DOT__u_nco__DOT__enable_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"invert_i", &(TOP.pdh_core__DOT__u_nco__DOT__invert_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"invert_r", &(TOP.pdh_core__DOT__u_nco__DOT__invert_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"next_phi1_w", &(TOP.pdh_core__DOT__u_nco__DOT__next_phi1_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"out1_o", &(TOP.pdh_core__DOT__u_nco__DOT__out1_o), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"out2_o", &(TOP.pdh_core__DOT__u_nco__DOT__out2_o), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"phi1_o", &(TOP.pdh_core__DOT__u_nco__DOT__phi1_o), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"phi1_pipe1_r", &(TOP.pdh_core__DOT__u_nco__DOT__phi1_pipe1_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"phi1_r", &(TOP.pdh_core__DOT__u_nco__DOT__phi1_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"phi2_o", &(TOP.pdh_core__DOT__u_nco__DOT__phi2_o), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"phi2_pipe1_r", &(TOP.pdh_core__DOT__u_nco__DOT__phi2_pipe1_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"phi2_w", &(TOP.pdh_core__DOT__u_nco__DOT__phi2_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rom1_lookup_w", &(TOP.pdh_core__DOT__u_nco__DOT__rom1_lookup_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rom1_signed_r", &(TOP.pdh_core__DOT__u_nco__DOT__rom1_signed_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rom1_signed_w", &(TOP.pdh_core__DOT__u_nco__DOT__rom1_signed_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rom2_intermediate_w", &(TOP.pdh_core__DOT__u_nco__DOT__rom2_intermediate_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rom2_lookup_w", &(TOP.pdh_core__DOT__u_nco__DOT__rom2_lookup_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rom2_signed_r", &(TOP.pdh_core__DOT__u_nco__DOT__rom2_signed_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rom2_signed_w", &(TOP.pdh_core__DOT__u_nco__DOT__rom2_signed_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"rst_i", &(TOP.pdh_core__DOT__u_nco__DOT__rst_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"shift_i", &(TOP.pdh_core__DOT__u_nco__DOT__shift_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"shift_r", &(TOP.pdh_core__DOT__u_nco__DOT__shift_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"state1_w", &(TOP.pdh_core__DOT__u_nco__DOT__state1_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"state2_w", &(TOP.pdh_core__DOT__u_nco__DOT__state2_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,1,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"stride_i", &(TOP.pdh_core__DOT__u_nco__DOT__stride_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"stride_r", &(TOP.pdh_core__DOT__u_nco__DOT__stride_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"sub_i", &(TOP.pdh_core__DOT__u_nco__DOT__sub_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco.varInsert(__Vfinal,"sub_r", &(TOP.pdh_core__DOT__u_nco__DOT__sub_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"AW", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__AW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"DW", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__DW))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"INIT_FILE", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__INIT_FILE))), true, VLVT_WDATA,VLVD_NODIR|VLVF_PUB_RW,0,1 ,167,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"addr1", &(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__addr1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"addr2", &(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__addr2), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,11,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"clk", &(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"dout1", &(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__dout1), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"dout2", &(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__dout2), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"i", &(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__i), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_nco__u_qtr_rom.varInsert(__Vfinal,"rom", &(TOP.pdh_core__DOT__u_nco__DOT__u_qtr_rom__DOT__rom), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,1,1 ,0,4095 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"DEC_W", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_pid__DOT__DEC_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"S16_W", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_pid__DOT__S16_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"S32_W", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_pid__DOT__S32_W))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"W1S", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_pid__DOT__W1S))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"W1U", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_pid__DOT__W1U))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"W2S", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_pid__DOT__W2S))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"W2U", const_cast<void*>(static_cast<const void*>(&(TOP.pdh_core__DOT__u_pid__DOT__W2U))), true, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW|VLVF_DPI_CLAY,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"alpha_i", &(TOP.pdh_core__DOT__u_pid__DOT__alpha_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"alpha_r", &(TOP.pdh_core__DOT__u_pid__DOT__alpha_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,3,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"clk", &(TOP.pdh_core__DOT__u_pid__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"cnt_r", &(TOP.pdh_core__DOT__u_pid__DOT__cnt_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"d_error_r", &(TOP.pdh_core__DOT__u_pid__DOT__d_error_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"d_error_shifted_w", &(TOP.pdh_core__DOT__u_pid__DOT__d_error_shifted_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"d_error_w", &(TOP.pdh_core__DOT__u_pid__DOT__d_error_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"dat_i", &(TOP.pdh_core__DOT__u_pid__DOT__dat_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"decimate_i", &(TOP.pdh_core__DOT__u_pid__DOT__decimate_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"decimate_r", &(TOP.pdh_core__DOT__u_pid__DOT__decimate_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"derr_tap", &(TOP.pdh_core__DOT__u_pid__DOT__derr_tap), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"enable_i", &(TOP.pdh_core__DOT__u_pid__DOT__enable_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"err_tap", &(TOP.pdh_core__DOT__u_pid__DOT__err_tap), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"error_pipe1_r", &(TOP.pdh_core__DOT__u_pid__DOT__error_pipe1_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"error_w", &(TOP.pdh_core__DOT__u_pid__DOT__error_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"i_error_r", &(TOP.pdh_core__DOT__u_pid__DOT__i_error_r), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"i_error_shifted_w", &(TOP.pdh_core__DOT__u_pid__DOT__i_error_shifted_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"i_error_w", &(TOP.pdh_core__DOT__u_pid__DOT__i_error_w), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,47,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"ierr_tap", &(TOP.pdh_core__DOT__u_pid__DOT__ierr_tap), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"kd_i", &(TOP.pdh_core__DOT__u_pid__DOT__kd_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"kd_r", &(TOP.pdh_core__DOT__u_pid__DOT__kd_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"ki_i", &(TOP.pdh_core__DOT__u_pid__DOT__ki_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"ki_r", &(TOP.pdh_core__DOT__u_pid__DOT__ki_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"kp_i", &(TOP.pdh_core__DOT__u_pid__DOT__kp_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"kp_r", &(TOP.pdh_core__DOT__u_pid__DOT__kp_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"next_cnt_w", &(TOP.pdh_core__DOT__u_pid__DOT__next_cnt_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"next_satwidth_w", &(TOP.pdh_core__DOT__u_pid__DOT__next_satwidth_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"p_error_r", &(TOP.pdh_core__DOT__u_pid__DOT__p_error_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"p_error_shifted_w", &(TOP.pdh_core__DOT__u_pid__DOT__p_error_shifted_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"p_error_w", &(TOP.pdh_core__DOT__u_pid__DOT__p_error_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"perr_tap", &(TOP.pdh_core__DOT__u_pid__DOT__perr_tap), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"pid_out", &(TOP.pdh_core__DOT__u_pid__DOT__pid_out), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"rst", &(TOP.pdh_core__DOT__u_pid__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sat_threshold_w", &(TOP.pdh_core__DOT__u_pid__DOT__sat_threshold_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"satwidth_i", &(TOP.pdh_core__DOT__u_pid__DOT__satwidth_i), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"satwidth_r", &(TOP.pdh_core__DOT__u_pid__DOT__satwidth_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,1 ,4,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sp_i", &(TOP.pdh_core__DOT__u_pid__DOT__sp_i), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sp_r", &(TOP.pdh_core__DOT__u_pid__DOT__sp_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,13,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sum_err_tap", &(TOP.pdh_core__DOT__u_pid__DOT__sum_err_tap), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sum_error1_w", &(TOP.pdh_core__DOT__u_pid__DOT__sum_error1_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sum_error2_w", &(TOP.pdh_core__DOT__u_pid__DOT__sum_error2_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sum_error_r", &(TOP.pdh_core__DOT__u_pid__DOT__sum_error_r), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,31,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"sum_error_wide_w", &(TOP.pdh_core__DOT__u_pid__DOT__sum_error_wide_w), false, VLVT_UINT64,VLVD_NODIR|VLVF_PUB_RW,0,1 ,32,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"tick1_r", &(TOP.pdh_core__DOT__u_pid__DOT__tick1_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"tick1_w", &(TOP.pdh_core__DOT__u_pid__DOT__tick1_w), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"tick2_r", &(TOP.pdh_core__DOT__u_pid__DOT__tick2_r), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"total_error_wide_w", &(TOP.pdh_core__DOT__u_pid__DOT__total_error_wide_w), false, VLVT_UINT32,VLVD_NODIR|VLVF_PUB_RW,0,1 ,19,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"yk_r", &(TOP.pdh_core__DOT__u_pid__DOT__yk_r), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_pid.varInsert(__Vfinal,"yk_w", &(TOP.pdh_core__DOT__u_pid__DOT__yk_w), false, VLVT_UINT16,VLVD_NODIR|VLVF_PUB_RW,0,1 ,15,0);
        __Vscope_pdh_core__u_strobe_edge_detector.varInsert(__Vfinal,"D", &(TOP.pdh_core__DOT__u_strobe_edge_detector__DOT__D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_strobe_edge_detector.varInsert(__Vfinal,"Q", &(TOP.pdh_core__DOT__u_strobe_edge_detector__DOT__Q), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_strobe_edge_detector.varInsert(__Vfinal,"clk", &(TOP.pdh_core__DOT__u_strobe_edge_detector__DOT__clk), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_strobe_edge_detector.varInsert(__Vfinal,"prev_D", &(TOP.pdh_core__DOT__u_strobe_edge_detector__DOT__prev_D), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
        __Vscope_pdh_core__u_strobe_edge_detector.varInsert(__Vfinal,"rst", &(TOP.pdh_core__DOT__u_strobe_edge_detector__DOT__rst), false, VLVT_UINT8,VLVD_NODIR|VLVF_PUB_RW,0,0);
    }
}
